"""
Hook Adapter
============
각 코딩 어시스턴트 CLI 도구별 후크 연결 어댑터
"""

from __future__ import annotations

import os
import sys
from abc import ABC, abstractmethod
from pathlib import Path
from typing import TYPE_CHECKING, Any, Callable, Optional

if TYPE_CHECKING:
    from ..core.manager import GeniusIntelligence


class HookAdapter(ABC):
    name: str = "generic"
    supported_tools: list[str] = []

    def __init__(self, genius: "GeniusIntelligence"):
        self.genius = genius
        self._installed = False

    @abstractmethod
    def install(self) -> bool:
        ...

    @abstractmethod
    def uninstall(self) -> bool:
        ...

    def is_compatible(self) -> bool:
        return True

    @classmethod
    def auto_detect(cls) -> Optional["HookAdapter"]:
        from ..core.manager import GeniusIntelligence
        genius = GeniusIntelligence.for_current_project()
        if genius is None:
            return None
        for adapter_cls in [ClaudeCodeAdapter, OMPAdapter, GenericAdapter]:
            adapter = adapter_cls(genius)
            if adapter.is_compatible():
                return adapter
        return GenericAdapter(genius)

    def _install_hooks(self, hooks: dict[str, Callable]) -> None:
        import json
        hooks_json = {
            name: f"{handler.__module__}.{handler.__qualname__}"
            for name, handler in hooks.items()
        }
        os.environ["GENIUS_INTELLIGENCE_HOOKS"] = json.dumps(hooks_json)
        os.environ["GENIUS_INTELLIGENCE_PROJECT"] = self.genius.project_root
        os.environ["GENIUS_INTELLIGENCE_ENABLED"] = "1"
        self._installed = True


class ClaudeCodeAdapter(HookAdapter):
    name = "claude-code"
    supported_tools = ["claude", "claude-code"]

    def install(self) -> bool:
        hooks = self.genius.get_hooks()
        hooks_config_dir = Path.home() / ".claude" / "hooks"
        hooks_config_dir.mkdir(parents=True, exist_ok=True)
        hooks_file = hooks_config_dir / "genius_intelligence_hooks.py"
        hooks_file.write_text(self._generate_hooks_file(), encoding="utf-8")
        self._install_hooks(hooks)
        return True

    def uninstall(self) -> bool:
        hooks_file = Path.home() / ".claude" / "hooks" / "genius_intelligence_hooks.py"
        if hooks_file.exists():
            hooks_file.unlink()
        return True

    def is_compatible(self) -> bool:
        return (
            os.environ.get("CLAUDE_API_KEY") is not None
            or any("claude" in a.lower() for a in sys.argv)
        )

    def _generate_hooks_file(self) -> str:
        return f"""# Auto-generated by GeniusIntelligence
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:
    from genius_intelligence.core import GeniusIntelligence
    genius = GeniusIntelligence.for_current_project()
    def on_message(msg, **kw): genius.on_user_message(str(msg), **kw)
    def on_response(resp, **kw): genius.on_assistant_message(str(resp), **kw)
    def on_command(cmd, success=True, **kw): genius.on_command_executed(str(cmd), success=success, **kw)
    def on_error(err, **kw): genius.on_error_occurred(str(err), **kw)
    def on_flush(): return genius.flush()
except ImportError:
    pass
"""


class OMPAdapter(HookAdapter):
    name = "omp"
    supported_tools = ["omp"]

    def install(self) -> bool:
        hooks = self.genius.get_hooks()
        project_root = self.genius.project_root
        hooks_dir = Path(project_root) / ".genius_intelligence" / "omp_hooks"
        hooks_dir.mkdir(parents=True, exist_ok=True)
        for hook_name, handler in hooks.items():
            hook_file = hooks_dir / f"{hook_name}.py"
            hook_file.write_text(f"# OMP Hook: {hook_name}\n", encoding="utf-8")
        self._install_hooks(hooks)
        return True

    def uninstall(self) -> bool:
        hooks_dir = Path(self.genius.project_root) / ".genius_intelligence" / "omp_hooks"
        if hooks_dir.exists():
            import shutil
            shutil.rmtree(hooks_dir)
        return True

    def is_compatible(self) -> bool:
        return (
            os.environ.get("OMP_CLI") is not None
            or Path(self.genius.project_root / ".omp.yaml").exists()
        )


class GenericAdapter(HookAdapter):
    name = "generic"
    supported_tools = ["*"]

    def install(self) -> bool:
        hooks = self.genius.get_hooks()
        self._install_hooks(hooks)
        return True

    def uninstall(self) -> bool:
        for key in ["GENIUS_INTELLIGENCE_HOOKS", "GENIUS_INTELLIGENCE_PROJECT", "GENIUS_INTELLIGENCE_ENABLED"]:
            os.environ.pop(key, None)
        return True

    def is_compatible(self) -> bool:
        return True